### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by Peppernose145** [Peppernose145/swds#1]
- [ ] Make Zenity optional
- [ ] Add support for Zenity alternatives (Like dialog, kdialog, and yad)
- [ ] Add custom prompt system for when none of the above are available
- [ ] Create a way to parse Steam Workshop URLs (Possible this could be a separate script)
